name: rpmtw_api_client
description: A starting point for Dart libraries or applications.
version: 1.0.1
homepage: https://www.rpmtw.com

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  byte_size:
    git: https://github.com/RPMTW/byte_size.git
  dio: ^4.0.4
