name: rpmtw_api_client
description: A starting point for Dart libraries or applications.
version: 1.0.6+4
homepage: https://www.rpmtw.com
repository: https://github.com/RPMTW/RPMTW-API-Client

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  collection: ^1.15.0
  http: ^0.13.4
  pub_semver: ^2.1.0
