name: rpmtw_api_client
description: RPMTW api client library for Dart
version: 1.0.9
homepage: https://www.rpmtw.com
repository: https://github.com/RPMTW/RPMTW-API-Client/tree/main/packages/rpmtw_api_client

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  collection: ^1.15.0
  http: ^0.13.4
  intl: ^0.17.0
  meta: ^1.7.0
  pub_semver: ^2.1.1
  socket_io_client: ^1.0.2
  universal_io: ^2.0.4
