name: Publish to Pub.dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publishing:
    if: ${{ !contains(github.event.head_commit.message,'[ci skip]]') && github.repository == 'RPMTW/RPMTW-API-Client'}}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Dart package rpmtw_api_client"
        uses: k-paxian/dart-package-publisher@5107bea93e50dba6afb494c449aaa816cf194c34
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: packages/rpmtw_api_client
          format: true
          skipTests: true
          force: true

      - name: "Dart package rpmtw_api_client_flutter"
        uses: k-paxian/dart-package-publisher@5107bea93e50dba6afb494c449aaa816cf194c34
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: packages/rpmtw_api_client_flutter
          format: true
          skipTests: true
          flutter: true
          force: true
