name: Publish to Pub.dev

on: push

jobs:
  publishing_rpmtw_api_client:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: 'Dart package'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: packages/rpmtw_api_client
          format: true